### ISSUE TITLE
Swift 3.0

### ISSUE THREAD

**Issue by tdouglas1313** [spxrogers/Moya-Gloss#12]
Are there any plans for this working with swift 3.0 on Xcode 8?

**Comment by spxrogers** [comment]
hey @tdouglas1313! yes yes yes, both this and it's [Alamofire sister](https://github.com/spxrogers/Alamofire-Gloss) will be updated to support Swift 3.

I am currently taking a short holiday, but am planning to release support sometime next week.

**Comment by bitomule** [comment]
Any update on this?

**Comment by spxrogers** [comment]
planning for tonight or tomorrow! :)

**Comment by spxrogers** [comment]
still working on this. project files are all updated to swift 3 syntax.
i'm seeing a lot of cocoapods errors when trying to release the new version. i'll likely spend a bit more time and if still no avail, reach out to some of the cocoapods members and other moya contributors to resolve some pod conflicts. 

hoping to have this update out soon, thanks for your patience @tdouglas1313 @bitomule & all.

**Comment by damianesteban** [comment]
This is the error that I'm currently getting:

```
[!] Unable to satisfy the following requirements:

- `Gloss (~> 1.0)` required by `Podfile`
- `Gloss (~> 0.7)` required by `Moya-Gloss/Core (1.1.0)`
```

**Comment by spxrogers** [comment]
thanks @damianesteban, I'm seeing a different but similar error. it'll help me debug transient issues in the morning

**Comment by spxrogers** [comment]
update: fixed some miscellaneous issues and getting a 2.0.0-beta.2 version ready. there's currently a small issue regarding the watchOS deployment target causing the cocoapod update to fail. 

i've opened an issue with the Moya team related to this here: https://github.com/Moya/Moya/issues/675

**Comment by spxrogers** [comment]
hey @tdouglas1313 @bitomule @damianesteban & all! 

i just pushed a beta release that _should_ be good to build! it's pre-release, so adding the following to your Podfile will pick up the beta version:

``` ruby
pod 'Moya-Gloss', :git => 'https://github.com/spxrogers/Moya-Gloss', :tag => '2.0.0-beta.3'
# or for reactive extensions
pod 'Moya-Gloss/RxSwift', :git => 'https://github.com/spxrogers/Moya-Gloss', :tag => '2.0.0-beta.3'
pod 'Moya-Gloss/ReactiveCocoa', :git => 'https://github.com/spxrogers/Moya-Gloss', :tag => '2.0.0-beta.3'
```

if there is any problems getting this version to build, feel free to bug me on this thread!

**Comment by spxrogers** [comment]
closing this now with the release of [2.0.0-beta.5](https://github.com/spxrogers/Moya-Gloss/releases/tag/2.0.0-beta.5) since things seem pretty stable(ish) and less frequently changing with Swift 3.0 versions in `Moya-Gloss`'s dependencies :clinking_glasses:
