### ISSUE TITLE
Dependency "Moya-Gloss" has no shared framework schemes

### ISSUE THREAD

**Issue by bitomule** [spxrogers/Moya-Gloss#15]
I get this issue trying to install with Carthage:

`Dependency "Moya-Gloss" has no shared framework schemes for any of the platforms: iOS`

Even tried pulling from "master" and got the same error. I've cloned the project and seems to have it's scheme shared. I don't know what the issues is.

**Comment by spxrogers** [comment]
hey @bitomule can you share the following so i can try to reproduce and investigate:
- carthage version
- cartfile content (only relevant parts necessary, if using some private libs)
- any other related carthage build errors, if any
