### ISSUE TITLE
Build failed with Carthage

### ISSUE THREAD

**Issue by bitomule** [spxrogers/Moya-Gloss#21]
I'm using XCode 8.3.2 and latest Carthage but can't add Moya-Gloos to my project. I get this error:

```
=== BUILD TARGET RxMoyaGloss OF PROJECT MoyaGloss WITH CONFIGURATION Release ===

Check dependencies
“Swift Language Version” (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly.
“Swift Language Version” (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly.

** BUILD FAILED **
```

**Comment by bitomule** [comment]
I think this PR fixes it but I also need the other PR to be merged in order to check if all works. https://github.com/spxrogers/Moya-Gloss/pull/22

**Comment by bitomule** [comment]
Ok, https://github.com/spxrogers/Moya-Gloss/pull/20 fixes issues. Please merge PR's

**Comment by spxrogers** [comment]
thanks for the update(s), @bitomule. 
i will follow up on the PR threads.

**Comment by bitomule** [comment]
I've pulled master again on another project and the issue seems to be back. What changed?

**Comment by bitomule** [comment]
Ok, the issue seems to be it's not published as a version yet no?

**Comment by spxrogers** [comment]
@bitomule—
**I'm still on Carthage version **0.20.1**.

I created a simple `Cartfile` with the content:
```
github "spxrogers/Moya-Gloss"
```

Running `carthage update` succeeded.

Corresponding `Cartfile.resolved`:
```
github "Alamofire/Alamofire" "4.4.0"
github "Moya/Moya" "8.0.4"
github "ReactiveCocoa/ReactiveSwift" "1.1.1"
github "ReactiveX/RxSwift" "3.4.1"
github "antitypical/Result" "3.2.1"
github "hkellaway/Gloss" "1.2.4"
github "spxrogers/Moya-Gloss" "2.0.1"
```

Are you resolving to the `2.0.1` release tag?

**Comment by bitomule** [comment]
Using "master" seems to work. I'll try to find when it fails because now it works 100%. Maybe it was some cache issue.
