### ISSUE TITLE
Framework not found ReactiveCocoa

### ISSUE THREAD

**Issue by bitomule** [spxrogers/Moya-Gloss#24]
I get this error after moving my project to RxSwift and removing ReactiveCocoa dependency from cart file. Do I have to add ReactiveCocoa as a dependency in my cartfile even if I don't use it?

**Comment by spxrogers** [comment]
hi @bitomule, it seems you didn't attach any error in the issue. please let me know so i can further investigate.

to answer the question too: no, you should not need reactive cocoa if you only want to use the base Moya-Gloss or RxSwift extension. you should only need to add `github "spxrogers/Moya-Gloss"` to your Cartfile and install (Moya declares both reactive projects explicitly in its own Cartfile so you'll get those dependencies out of the box). it will compile three frameworks (`MoyaGloss`, `RxMoyaGloss`, and `ReactiveMoyaGloss`), you should only import/link the **one** you desire.

**Comment by bitomule** [comment]
Hi @spxrogers , sorry. This is the error I get when I do a cat of the log from Carthage build:

```
ld: framework not found ReactiveCocoa
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

And this are my Carthage dependencies:

```
github "ReactiveX/RxSwift" ~> 3.0
github "AliSoftware/Reusable"
github "patchthecode/JTAppleCalendar"
github "bitomule/Moya-Gloss" "master"
github "aschuch/AwesomeCache"
github "RxSwiftCommunity/RxRealm"
```

**Comment by spxrogers** [comment]
@bitomule i see you're using your own fork of `Moya-Gloss`.
quickly glancing at your latest pull from mine, you are building version 2.0.0 which is behind the latest patch (2.0.1) containing fixes for Carthage build errors.

version 2.0.1 _might_ resolve your issues for you. please update and reply on this issue if that helps or not. if you're still getting the same error (or a new one) i'll investigate further. 
also please keep in mind i cannot manage bug fixes on remote forks from the core repository, it'll add too much for me to try and track + manage.

**Comment by bitomule** [comment]
Omg, I'm stupid. I'm sorry @spxrogers , the issue was using the fork. I don't remember why I started using it...

**Comment by spxrogers** [comment]
no worries @bitomule! i'm glad the latest version solved your issues :) 

i welcome and love community PRs for fixes / Swift version updates and i always try to always get to them. unfortunately, with my schedule the past few months my average time to response ranges anywhere between 1-3wks, so that's caused a few forks for updates that i was slow to merge—so i can understand why you might have been doing such
