### ISSUE TITLE
Gloss Decodable/Encodable Namespace

### ISSUE THREAD

**Issue by cohen72** [spxrogers/Moya-Gloss#25]
Can you please update the library to rename all references to Decodable and Encodable to include Gloss namespace:

Gloss.Decodable
Gloss.Encodable

Thanks!

**Comment by spxrogers** [comment]
hi @cohen72, there is a PR #23 that addresses this. it looks good, and expect a new CP+Carthage release this weekend.

**Comment by spxrogers** [comment]
following up on this @cohen72: version 2.0.2 was just released with this fix addressed.

+thank you @saeros for the initial find and base extension PR fix.

**Comment by spxrogers** [comment]
this is now released in the [2.0.3](https://github.com/spxrogers/Moya-Gloss/releases/tag/2.0.3) version.
