### ISSUE TITLE
Moya 9 support

### ISSUE THREAD

**Issue by dtomicAZ** [spxrogers/Moya-Gloss#27]
Hi,

does Moya-Gloss supports Moya 9 ?

**Comment by spxrogers** [comment]
hi @dtomicAZ, not yet. 
there will be a new version soon for Moya 9

**Comment by spxrogers** [comment]
hi @dtomicAZ—Moya just released a [10-beta](https://github.com/Moya/Moya/releases/tag/10.0.0-beta.1) and I am evaluating skipping the version 9 support in preference of v10, especially with the recent Swift 4 release.

i'll update this issue in a couple days with new info

**Comment by spxrogers** [comment]
@dtomicAZ—i am working on the Moya 10 support now, and closing this in favor of the upcoming release.
