### ISSUE TITLE
Swift 4 support

### ISSUE THREAD

**Issue by GabrielAraujo** [spxrogers/Moya-Gloss#29]
Any plans on adding swift 4 support?

**Comment by spxrogers** [comment]
I am working on Swift 4 support now, and will release a new `Moya-Gloss` version for that soon. 

It will also be targeting `Gloss-2` and `Moya-10`

**Comment by spxrogers** [comment]
[v3.0.0](https://github.com/spxrogers/Moya-Gloss/releases/tag/3.0.0) was just released @GabrielAraujo. it targets Swift 4, Gloss 2, and Moya 10.

cheers.
