### ISSUE TITLE
Request structure

### ISSUE THREAD

**Issue by GabrielAraujo** [spxrogers/Moya-Gloss#30]
Hello,

When I look at the moya documentation it tells to perform RxSwift requests with provider.rx.request ... but In the Moya-Gloss documentation it uses directly the provider.request. Do you know why?

**Comment by GabrielAraujo** [comment]
Ignore it.. I looked at the demo project and understood how you have done it..

**Comment by spxrogers** [comment]
glad you were able to find the answer @GabrielAraujo—i am also in the middle of updating the README/docs to be more clear and detailed to hopefully mitigate future ambiguities :)
