### ISSUE TITLE
Unable to get RxMoyaGloss to compile locally

### ISSUE THREAD

**Issue by AndrewSB** [spxrogers/Moya-Gloss#9]
Checked out master, built dependencies with `carthage build`, am getting errors in `Observable+Gloss.swift` saying `ambiguous use of <MoyaGloss method>

![screen shot 2016-05-31 at 3 53 10 pm](https://cloud.githubusercontent.com/assets/3814772/15693151/f79dc1ac-2747-11e6-8b97-4652b933e127.png)

any guidance on getting Observable+Gloss to compile?

**Comment by spxrogers** [comment]
funky, let me look into it. 

cc: @AndrewSB

**Comment by spxrogers** [comment]
@AndrewSB can you tell me which of the relevant (RxMoyaGloss, Gloss, etc...) frameworks you're linking in your project? So I can match your configuration to debug

**Comment by AndrewSB** [comment]
I did a `carthage build`, so whatever was in the resolved file. Pasted here:

```
github "Alamofire/Alamofire" "3.3.1"
github "hkellaway/Gloss" "0.7.2"
github "antitypical/Result" "2.0.0"
github "ReactiveX/RxSwift" "2.4"
github "ReactiveCocoa/ReactiveCocoa" "v4.1.0"
github "Moya/Moya" "6.4.0"
```

**Comment by AndrewSB** [comment]
```
/Users/asb/Developer/<proj name>/Carthage/Checkouts/Moya-Gloss/Source/RxSwift/Observable+Gloss.swift:21:34: error: ambiguous use of 'mapObject'
/Users/asb/Developer/<proj name>/Carthage/Checkouts/Moya-Gloss/Source/RxSwift/Observable+Gloss.swift:29:34: error: ambiguous use of 'mapArray'
A shell task (/usr/bin/xcrun xcodebuild -project /Users/asb/Developer/<proj name>/Carthage/Checkouts/Moya-Gloss/MoyaGloss.xcodeproj -scheme RxMoyaGloss -configuration Release -sdk iphoneos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean build) failed with exit code 65:
** BUILD FAILED **
```

update: now failing with a regular carthage update from an unrelated project. Maybe an update on Moya broke this?

**Comment by AndrewSB** [comment]
@spxrogers do let me know if theres anything I can help with!

**Comment by AndrewSB** [comment]
@spxrogers this is now blocking the projects I'm working on that use `Moya-Gloss`. The sooner we can fix this the better!

**Comment by spxrogers** [comment]
@AndrewSB so I've peeked a bit into this, and I'm not experiencing this ambiguous error with current master branch version. 

can you verify that you're not double-linking frameworks? i.e.: i setup Moya-Gloss in a similar pattern as Moya so you only need to link `RxMoyaGloss.framework` plus `RxMoya.framework` and **not** the default `MoyaGloss.framework` & `Moya.framework` as shown below: 
![img](http://i.imgur.com/wtSEgWE.png)

let me know. 

(PS, sorry for more delayed responses, just work got busy and in middle of a move)

**Comment by spxrogers** [comment]
@AndrewSB did you investigate your linked framework to ensure you aren't double-linking? 
let me me know, i'm tempted to close this as "not reproducible" otherwise.

**Comment by spxrogers** [comment]
closed as not reproducible. ping me again / re-open if this issue comes up again @anyone
